#!/usr/bin/env python3
"""checkmk-tuning-check.py - Checks the status of Nagios/CheckMK RAW tuning
and automatically applies the fix if necessary.

Diagnosis logic:
  - Reads tuning.cfg and collects CPU, number of services, load
  - Calculate the optimal value of max_concurrent_checks (CPU * 25)
  - If current value exceeds safe threshold (> CPU * 50) → FIX needed
  - With --fix: rewrite tuning.cfg and restart omd

Usage:
    python3 checkmk-tuning-check.py # diagnosis only
    python3 checkmk-tuning-check.py --fix # diagnosis + automatic fix if needed
    python3 checkmk-tuning-check.py --fix --yes # fix without interactive confirmation

Environment:
    SITE=monitoring (default)

Version: 1.0.0"""

import argparse
import datetime as dt
import grp
import os
import pwd
import shutil
import subprocess
import sys
from pathlib import Path

VERSION = "1.0.0"

# ── Soglie ──────────────────────────────────────────────────────────────────
# max_concurrent_checks ottimale = CPU * 25
# max_concurrent_checks too high = CPU * 50 → FLAG for fix
OPTIMAL_RATIO = 25
WARN_RATIO = 50


# ── Helpers ──────────────────────────────────────────────────────────────────

def log(msg: str) -> None:
    print(f"[INFO] {msg}")


def warn(msg: str) -> None:
    print(f"[WARN] {msg}")


def ok(msg: str) -> None:
    print(f"[ OK ] {msg}")


def err(msg: str) -> None:
    print(f"[ERR ] {msg}", file=sys.stderr)


def die(msg: str) -> None:
    err(msg)
    raise SystemExit(1)


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def read_cfg_int(key: str, path: Path, fallback: int = 0) -> int:
    if not path.exists():
        return fallback
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if line.startswith(f"{key}="):
            try:
                return int(line.split("=", 1)[1].strip())
            except ValueError:
                return fallback
    return fallback


def read_cfg_str(key: str, path: Path, fallback: str = "") -> str:
    if not path.exists():
        return fallback
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if line.startswith(f"{key}="):
            return line.split("=", 1)[1].strip()
    return fallback


def count_services(objects_cache: Path) -> int:
    if not objects_cache.exists():
        return 0
    count = 0
    for line in objects_cache.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.strip() == "define service {":
            count += 1
    return count


def get_cpu_count() -> int:
    try:
        return os.cpu_count() or 2
    except Exception:
        return 2


def get_load_avg() -> float:
    try:
        return os.getloadavg()[0]
    except Exception:
        return 0.0


def backup_file(path: Path) -> Path:
    ts = dt.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    backup = path.parent / f"{path.name}.backup_{ts}"
    shutil.copy2(path, backup)
    # monitoring:monitoring 660 permissions
    try:
        uid = pwd.getpwnam("monitoring").pw_uid
        gid = grp.getgrnam("monitoring").gr_gid
        os.chown(backup, uid, gid)
        os.chmod(backup, 0o660)
    except Exception:
        pass
    return backup


def write_tuning_cfg(path: Path, cpu: int, services: int, load: float,
                     concurrent: int, serv_timeout: int, host_timeout: int,
                     sleep_time: str, delay_method: str) -> None:
    content = (
        f"# Generated by checkmk-tuning-check.py on {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# max_concurrent_checks={concurrent} (load {load:.2f}, {cpu} CPU, {services} servizi - fix stale)\n"
        f"max_concurrent_checks={concurrent}\n"
        f"service_check_timeout={serv_timeout}\n"
        f"host_check_timeout={host_timeout}\n"
        f"sleep_time={sleep_time}\n"
        f"service_inter_check_delay_method={delay_method}\n"
    )
    path.write_text(content, encoding="utf-8")
    try:
        uid = pwd.getpwnam("monitoring").pw_uid
        gid = grp.getgrnam("monitoring").gr_gid
        os.chown(path, uid, gid)
        os.chmod(path, 0o660)
    except Exception:
        pass


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description=f"checkmk-tuning-check.py v{VERSION} - Diagnosi e fix tuning Nagios/CheckMK"
    )
    parser.add_argument("--fix", action="store_true",
                        help="Applica il fix se il tuning è fuori soglia")
    parser.add_argument("--yes", "-y", action="store_true",
                        help="Non chiedere conferma prima del fix")
    args = parser.parse_args()

    if os.geteuid() != 0:
        die("eseguire come root")

    site = os.environ.get("SITE", "monitoring")
    site_path = Path(f"/opt/omd/sites/{site}")
    if not site_path.is_dir():
        die(f"sito OMD non trovato: {site_path}")

    nagios_cfg = site_path / "etc/nagios/nagios.d/tuning.cfg"
    objects_cache = site_path / "var/nagios/objects.cache"

    print(f"checkmk-tuning-check.py v{VERSION}")
    print(f"Sito: {site}  |  {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    # ── Raccolta dati ────────────────────────────────────────────────────────
    cpu = get_cpu_count()
    load = get_load_avg()
    services = count_services(objects_cache)

    current_concurrent = read_cfg_int("max_concurrent_checks", nagios_cfg, fallback=0)
    current_serv_tmout = read_cfg_int("service_check_timeout", nagios_cfg, fallback=60)
    current_host_tmout = read_cfg_int("host_check_timeout", nagios_cfg, fallback=60)
    current_sleep = read_cfg_str("sleep_time", nagios_cfg, fallback="0.25")
    current_delay = read_cfg_str("service_inter_check_delay_method", nagios_cfg, fallback="s")

    optimal = cpu * OPTIMAL_RATIO
    threshold = cpu * WARN_RATIO

    print("── SISTEMA ────────────────────────────────────")
    print(f"  CPU:                {cpu}")
    print(f"  Load avg (1min):    {load:.2f}")
    print(f"  Servizi monitorati: {services}")
    print()
    print("── TUNING.CFG ATTUALE ─────────────────────────")
    if not nagios_cfg.exists():
        warn(f"  tuning.cfg non trovato: {nagios_cfg}")
        current_concurrent = 0
    else:
        print(f"  max_concurrent_checks:            {current_concurrent}")
        print(f"  service_check_timeout:            {current_serv_tmout}s")
        print(f"  host_check_timeout:               {current_host_tmout}s")
        print(f"  sleep_time:                       {current_sleep}")
        print(f"  service_inter_check_delay_method: {current_delay}")
    print()
    print("── ANALISI ────────────────────────────────────")
    print(f"  Valore ottimale  (CPU × {OPTIMAL_RATIO}): {optimal}")
    print(f"  Soglia attenzione (CPU × {WARN_RATIO}): {threshold}")
    print(f"  Valore attuale:                {current_concurrent}")
    print()

    needs_fix = current_concurrent == 0 or current_concurrent > threshold

    if not needs_fix:
        ok(f"Tuning OK — max_concurrent_checks={current_concurrent} è entro la soglia ({threshold})")
        print()
        return 0

    # ── Fix necessario ───────────────────────────────────────────────────────
    warn(f"max_concurrent_checks={current_concurrent} supera la soglia ({threshold}) → FIX necessario")
    print(f"  Valore corretto da applicare: {optimal}")
    print()

    if not args.fix:
        print("Per applicare il fix eseguire con --fix")
        print(f"  python3 {Path(__file__).name} --fix")
        return 1

    if not args.yes:
        resp = input(f"Applicare fix (max_concurrent_checks={optimal}) e riavviare omd? [y/N]: ").strip().lower()
        if resp != "y":
            log("Annullato")
            return 0

    # backup
    if nagios_cfg.exists():
        backup = backup_file(nagios_cfg)
        log(f"Backup: {backup}")

    # write new tuning.cfg
    write_tuning_cfg(
        path=nagios_cfg,
        cpu=cpu, services=services, load=load,
        concurrent=optimal,
        serv_timeout=current_serv_tmout or 60,
        host_timeout=current_host_tmout or 60,
        sleep_time=current_sleep or "0.25",
        delay_method=current_delay or "s",
    )
    log(f"tuning.cfg riscritto con max_concurrent_checks={optimal}")

    # omd reboot
    log(f"Riavvio sito OMD: {site}")
    result = run(["omd", "restart", site])
    if result.stdout:
        print(result.stdout.strip())
    if result.stderr:
        print(result.stderr.strip(), file=sys.stderr)

    if result.returncode != 0:
        err("omd restart ha restituito errore!")
        return 1

    print()
    ok(f"Fix applicato. max_concurrent_checks: {current_concurrent} → {optimal}")
    ok("Attendi 1-2 minuti e verifica la UI CheckMK.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
