#!/usr/bin/env python3
"""checkmk-tuning-interactive.py

Interactive (simple) tuning for Checkmk RAW / OMD (Nagios core).
Version: 1.0.0"""

import datetime as dt
import os
import shutil
import subprocess
import sys
from pathlib import Path

VERSION = "1.0.0"


def usage() -> None:
    print(
        "Usage:\n"
        "  checkmk-tuning-interactive.py\n\n"
        "Environment:\n"
        "  SITE (default: monitoring)\n"
    )


def die(message: str) -> None:
    print(f"[ERR] {message}", file=sys.stderr)
    raise SystemExit(1)


def log(message: str) -> None:
    print(f"[INFO] {message}")


def warn(message: str) -> None:
    print(f"[WARN] {message}")


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def require_root() -> None:
    if os.geteuid() != 0:
        die("eseguire come root (sudo)")


def need_cmd(command: str) -> None:
    if shutil.which(command) is None:
        die(f"comando mancante: {command}")


def read_cfg_value(key: str, file_path: Path) -> str:
    if not file_path.exists():
        return "(non impostato)"
    for line in file_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith(f"{key}="):
            value = line.split("=", 1)[1].strip()
            return value if value else "(non impostato)"
    return "(non impostato)"


def ensure_global_mk_line(global_mk: Path, line: str) -> None:
    global_mk.parent.mkdir(parents=True, exist_ok=True)
    if not global_mk.exists():
        global_mk.write_text("", encoding="utf-8")

    lines = global_mk.read_text(encoding="utf-8", errors="ignore").splitlines()
    if line not in lines:
        with global_mk.open("a", encoding="utf-8") as handle:
            handle.write(line + "\n")


def prompt_default(text: str, default: str) -> str:
    value = input(f"{text} [{default}]: ").strip()
    return value if value else default


def main() -> int:
    if any(arg in {"-h", "--help"} for arg in sys.argv[1:]):
        usage()
        return 0

    require_root()
    need_cmd("omd")

    site = os.environ.get("SITE", "monitoring")
    site_path = Path(f"/opt/omd/sites/{site}")
    nagios_cfg = site_path / "etc/nagios/nagios.d/tuning.cfg"
    global_mk = site_path / "etc/check_mk/conf.d/wato/global.mk"

    if not site_path.is_dir():
        die(f"sito non trovato: {site} ({site_path})")

    backup_dir = Path(f"/root/checkmk_tuning_backup_{dt.datetime.now().strftime('%Y%m%d_%H%M%S')}")
    backup_dir.mkdir(parents=True, exist_ok=True)

    if nagios_cfg.exists():
        shutil.copy2(nagios_cfg, backup_dir / nagios_cfg.name)
    if global_mk.exists():
        shutil.copy2(global_mk, backup_dir / global_mk.name)

    print("Checkmk tuning (interactive)")
    print(f"Sito:   {site}")
    print(f"Backup: {backup_dir}")
    print()

    current_conc = read_cfg_value("max_concurrent_checks", nagios_cfg)
    current_serv_tmout = read_cfg_value("service_check_timeout", nagios_cfg)
    current_host_tmout = read_cfg_value("host_check_timeout", nagios_cfg)
    current_sleep = read_cfg_value("sleep_time", nagios_cfg)
    current_delay = read_cfg_value("service_inter_check_delay_method", nagios_cfg)

    print(f"Impostazioni attuali ({nagios_cfg}):")
    print(f"  max_concurrent_checks            = {current_conc}")
    print(f"  service_check_timeout            = {current_serv_tmout}")
    print(f"  host_check_timeout               = {current_host_tmout}")
    print(f"  sleep_time                       = {current_sleep}")
    print(f"  service_inter_check_delay_method = {current_delay}")
    print()

    print("Inserisci i nuovi valori (invio = default suggerito)")
    new_conc = prompt_default("max_concurrent_checks", "30")
    new_serv_tmout = prompt_default("service_check_timeout (sec)", "60")
    new_host_tmout = prompt_default("host_check_timeout (sec)", "60")
    new_sleep = prompt_default("sleep_time (sec)", "0.25")
    new_delay = prompt_default("inter_check_delay_method (n/s/d)", "s")

    print()
    print("Riepilogo nuovi valori:")
    print(f"  max_concurrent_checks            = {new_conc}")
    print(f"  service_check_timeout            = {new_serv_tmout}")
    print(f"  host_check_timeout               = {new_host_tmout}")
    print(f"  sleep_time                       = {new_sleep}")
    print(f"  service_inter_check_delay_method = {new_delay}")
    print()

    confirm = input("Applicare queste modifiche? [y/N]: ").strip().lower() or "n"
    if confirm != "y":
        log("Annullato")
        return 0

    nagios_cfg.parent.mkdir(parents=True, exist_ok=True)
    content = (
        f"# Generated by checkmk-tuning-interactive.py on {dt.datetime.now().strftime('%F_%T')}\n"
        f"max_concurrent_checks={new_conc}\n"
        f"service_check_timeout={new_serv_tmout}\n"
        f"host_check_timeout={new_host_tmout}\n"
        f"sleep_time={new_sleep}\n"
        f"service_inter_check_delay_method={new_delay}\n"
    )
    nagios_cfg.write_text(content, encoding="utf-8")

    ensure_global_mk_line(global_mk, f"service_check_timeout = {new_serv_tmout}")
    ensure_global_mk_line(global_mk, "use_cache_for_checking = True")

    log(f"Riavvio sito: {site}")
    restart = run(["omd", "restart", site], check=False)
    if restart.stdout:
        print(restart.stdout.strip())
    if restart.stderr:
        print(restart.stderr.strip(), file=sys.stderr)

    nagios_log = site_path / "var/nagios/nagios.log"
    print()
    if nagios_log.exists():
        print(f"Ultime righe log Nagios ({nagios_log}):")
        tail = run(["tail", "-n", "10", str(nagios_log)], check=False)
        if tail.stdout:
            print(tail.stdout.strip())
    else:
        warn(f"Log Nagios non trovato: {nagios_log}")

    print()
    log(f"Completato. Backup: {backup_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
