#!/usr/bin/env python3
"""acl-viewer.py - Samba Share NS8 ACL Viewer

Reads *_smbacl.txt files generated by NS8 audit scripts
and shows the permissions in readable Italian format.

Usage: ./acl-viewer.py [audit_directory]

If not specified, use the latest audit in /var/tmp/ns8-audit-*

Version: 1.0.0"""

import sys
import re
from pathlib import Path
from typing import Optional, List, Tuple

VERSION = "1.0.0"


def translate_permissions(perms: str) -> str:
    """Translate Windows permissions to Italian description.
    
    Args:
        perms: Permission string from Windows ACL
        
    Returns:
        Italian permission description"""
    perms_upper = perms.upper()
    
    if "FULL" in perms_upper or "0x001f01ff" in perms_upper:
        return "Controllo Totale"
    elif "RWXD" in perms_upper or "0x001301bf" in perms_upper:
        return "Lettura e Scrittura"
    elif "READ" in perms_upper or "0x00120089" in perms_upper:
        return "Solo Lettura"
    else:
        return f"Permessi: {perms}"


def find_latest_audit_dir() -> Optional[Path]:
    """Find most recent audit directory in /var/tmp.
    
    Returns:
        Path to latest audit directory or None if not found"""
    base_path = Path("/var/tmp")
    if not base_path.exists():
        return None
    
    # Find all ns8-audit-* directories
    audit_dirs = sorted(
        [d for d in base_path.glob("ns8-audit-*") if d.is_dir()],
        reverse=True
    )
    
    return audit_dirs[0] if audit_dirs else None


def parse_acl_line(acl_line: str) -> Tuple[str, str]:
    """Parse ACL line to extract entity and permissions.
    
    Args:
        acl_line: ACL line (format: ACL:DOMAIN\\entity:ALLOWED/flags/perms)
        
    Returns:
        Tuple of (entity, permissions)"""
    parts = acl_line.split(':')
    if len(parts) >= 3:
        entity = parts[1]
        perms_part = parts[2].split('/')
        perms = perms_part[2] if len(perms_part) >= 3 else ""
        return entity, perms
    return "", ""


def get_share_path(share_name: str, shares_report: Path) -> str:
    """Get share path from shares_report.tsv.
    
    Args:
        share_name: Share name
        shares_report: Path to shares_report.tsv
        
    Returns:
        Share path or empty string if not found"""
    if not shares_report.exists():
        return ""
    
    try:
        with open(shares_report, 'r', encoding='utf-8') as f:
            for line in f:
                if line.startswith(share_name + '\t'):
                    parts = line.strip().split('\t')
                    return parts[1] if len(parts) >= 2 else ""
    except (IOError, UnicodeDecodeError):
        pass
    
    return ""


def display_acl_report(audit_dir: Path) -> int:
    """Display ACL report for all shares in audit directory.
    
    Args:
        audit_dir: Path to audit directory
        
    Returns:
        Exit code (0=success, 1=error)"""
    acl_dir = audit_dir / "03_shares" / "acls"
    
    if not acl_dir.is_dir():
        print(f"[ERR] Directory ACL non trovata: {acl_dir}", file=sys.stderr)
        return 1
    
    shares_report = audit_dir / "03_shares" / "shares_report.tsv"
    
    # Header
    print()
    print("=" * 115)
    print("  REPORT PERMESSI SHARE NS8")
    print("=" * 115)
    print()
    print(f"Audit directory: {audit_dir}")
    print()
    
    # Table header
    print(f"{'SHARE':<20} {'PERCORSO':<35} {'ENTITA':<30} {'PERMESSI':<25}")
    print(f"{'-'*20} {'-'*35} {'-'*30} {'-'*25}")
    
    # Process all ACL files
    share_count = 0
    acl_files = sorted(acl_dir.glob("*_smbacl.txt"))
    
    for acl_file in acl_files:
        share_name = acl_file.stem.replace("_smbacl", "")
        share_count += 1
        
        # Get share path
        share_path = get_share_path(share_name, shares_report)[:35]
        
        # Read ACL file
        try:
            with open(acl_file, 'r', encoding='utf-8', errors='ignore') as f:
                acl_lines = [
                    line.strip() for line in f
                    if line.startswith("ACL:") and not re.search(r"^ACL:(NT AUTHORITY|BUILTIN)", line)
                ]
        except IOError:
            continue
        
        if not acl_lines:
            # Share without user permissions
            print(f"{share_name:<20} {share_path:<35} {'[solo sistema]':<30} {'-':<25}")
            continue
        
        # Process each ACL entry
        first_line = True
        for acl_line in acl_lines:
            entity, perms = parse_acl_line(acl_line)
            if not entity:
                continue
            
            perms_italian = translate_permissions(perms)
            
            if first_line:
                print(f"{share_name:<20} {share_path:<35} {entity[:30]:<30} {perms_italian:<25}")
                first_line = False
            else:
                print(f"{'':20} {'':35} {entity[:30]:<30} {perms_italian:<25}")
    
    # Footer
    print()
    print("=" * 115)
    print(f"Totale share analizzate: {share_count}")
    print()
    print("NOTE:")
    print("  - Per vedere i membri di un gruppo AD:")
    print("    runagent -m samba1 podman exec samba-dc samba-tool group listmembers NOME_GRUPPO")
    print()
    
    return 0


def main() -> int:
    """Main entry point.
    
    Returns:
        Exit code"""
    audit_dir = None
    
    # Parse command line argument
    if len(sys.argv) > 1:
        audit_dir = Path(sys.argv[1])
    else:
        # Find latest audit directory
        audit_dir = find_latest_audit_dir()
        if not audit_dir:
            print("[ERR] Nessuna directory audit trovata in /var/tmp/ns8-audit-*", file=sys.stderr)
            return 1
        print(f"[INFO] Uso audit directory: {audit_dir}")
    
    if not audit_dir.is_dir():
        print(f"[ERR] Directory non trovata: {audit_dir}", file=sys.stderr)
        return 1
    
    return display_acl_report(audit_dir)


if __name__ == "__main__":
    sys.exit(main())
